version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn server:app --host 0.0.0.0 --port 8000

  updater:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    command: python update_remote_db.py
